//! Interoperability with OpenSSL (3.5 or later), in both directions.
//!
//! * IronSocketLayer client ↔ `openssl s_server`, with keys and certificates
//!   generated by OpenSSL and loaded through IronSocketLayer' PKCS#8 path.
//! * `openssl s_client` ↔ IronSocketLayer server, with certificates minted by
//!   IronSocketLayer' own certificate builder and verified by OpenSSL.
//!
//! Covers every implemented group — including X25519MLKEM768,
//! SecP256r1MLKEM768, SecP384r1MLKEM1024 and pure ML-KEM-768 and
//! ML-KEM-1024 — and every key type, ML-DSA-65
//! included. Ignored by default because it needs `openssl` on PATH:
//! `cargo test -p iron-socket-layer --test openssl_interop -- --ignored --test-threads=1`.

mod common;

use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::sync::Arc;
use std::time::{Duration, Instant};

use common::Pki;
use iron_socket_layer::config::{
    ClientAuth, ClientConfig, Identity, PeerVerification, Profile, ServerConfig,
};
use iron_socket_layer::crypto::sign::{KeyKind, SigningKey};
use iron_socket_layer::enums::NamedGroup;
use iron_socket_layer::report::Property;
use iron_socket_layer::stream::TlsStream;
use iron_socket_layer::x509::RootStore;

/// OpenSSL's names for the groups IronSocketLayer implements.
const GROUPS: &[(NamedGroup, &str)] = &[
    (NamedGroup::X25519MlKem768, "X25519MLKEM768"),
    (NamedGroup::SecP256r1MlKem768, "SecP256r1MLKEM768"),
    (NamedGroup::MlKem768, "MLKEM768"),
    (NamedGroup::SecP384r1MlKem1024, "SecP384r1MLKEM1024"),
    (NamedGroup::MlKem1024, "MLKEM1024"),
    (NamedGroup::X25519, "x25519"),
    (NamedGroup::Secp256r1, "P-256"),
    (NamedGroup::Secp384r1, "P-384"),
    (NamedGroup::Secp521r1, "P-521"),
];

/// `openssl req -newkey` arguments for each key type.
const KEYS: &[(&str, &[&str])] = &[
    (
        "ecdsa-p256",
        &["-newkey", "ec", "-pkeyopt", "ec_paramgen_curve:P-256"],
    ),
    (
        "ecdsa-p384",
        &["-newkey", "ec", "-pkeyopt", "ec_paramgen_curve:P-384"],
    ),
    (
        "ecdsa-p521",
        &["-newkey", "ec", "-pkeyopt", "ec_paramgen_curve:P-521"],
    ),
    ("ed25519", &["-newkey", "ed25519"]),
    ("rsa-2048", &["-newkey", "rsa:2048"]),
    ("ml-dsa-65", &["-newkey", "ML-DSA-65"]),
];

fn workdir(name: &str) -> PathBuf {
    let d = std::env::temp_dir()
        .join("iron-socket-layer-openssl")
        .join(name);
    std::fs::create_dir_all(&d).unwrap();
    d
}

fn openssl(args: &[&str], dir: &Path) -> std::process::Output {
    Command::new("openssl")
        .args(args)
        .current_dir(dir)
        .output()
        .expect("openssl on PATH")
}

fn free_port() -> u16 {
    TcpListener::bind("127.0.0.1:0")
        .unwrap()
        .local_addr()
        .unwrap()
        .port()
}

/// Self-signed end-entity certificate for server.test, made by OpenSSL.
fn openssl_identity(dir: &Path, key_args: &[&str]) {
    let mut args = vec![
        "req", "-x509", "-nodes", "-days", "2", "-keyout", "key.pem", "-out", "cert.pem",
    ];
    args.extend_from_slice(key_args);
    args.extend_from_slice(&[
        "-subj",
        "/CN=server.test",
        "-addext",
        "subjectAltName=DNS:server.test",
        "-addext",
        "basicConstraints=critical,CA:FALSE",
        "-addext",
        "keyUsage=critical,digitalSignature",
        "-addext",
        "extendedKeyUsage=serverAuth,clientAuth",
    ]);
    let out = openssl(&args, dir);
    assert!(
        out.status.success(),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
}

fn pem_to_der(pem: &str) -> Vec<u8> {
    let mut buf = vec![0u8; pem.len()];
    let n = ic_pkix::pem::decode(ic_pkix::pem::CERTIFICATE, pem.as_bytes(), &mut buf).unwrap();
    buf.truncate(n);
    buf
}

fn der_to_pem(der: &[u8]) -> String {
    let mut buf = vec![0u8; ic_pkix::pem::encoded_len(ic_pkix::pem::CERTIFICATE, der.len())];
    let n = ic_pkix::pem::encode(ic_pkix::pem::CERTIFICATE, der, &mut buf).unwrap();
    String::from_utf8(buf[..n].to_vec()).unwrap()
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn our_client_against_openssl_server_for_every_key_and_group() {
    for (key_name, key_args) in KEYS {
        let dir = workdir(key_name);
        openssl_identity(&dir, key_args);
        // OpenSSL's PKCS#8 must load through our parser, and match its certificate.
        let key = SigningKey::from_pem(&std::fs::read_to_string(dir.join("key.pem")).unwrap())
            .unwrap_or_else(|e| panic!("{key_name}: {e}"));
        let cert_pem = std::fs::read_to_string(dir.join("cert.pem")).unwrap();
        let cert_der = pem_to_der(&cert_pem);
        Identity::new(vec![cert_der.clone()], key).unwrap_or_else(|e| panic!("{key_name}: {e}"));
        let mut roots = RootStore::new();
        roots.add_der(&cert_der).unwrap();

        for (group, ossl_group) in GROUPS {
            let mut cfg = ClientConfig::new(Profile::Default, roots.clone()).unwrap();
            cfg.common.groups = vec![*group];
            cfg.initial_key_shares = 1;
            let port = free_port();
            let mut server = Command::new("openssl")
                .args([
                    "s_server",
                    "-accept",
                    &port.to_string(),
                    "-tls1_3",
                    "-groups",
                    ossl_group,
                    "-key",
                    "key.pem",
                    "-cert",
                    "cert.pem",
                    "-www",
                    "-naccept",
                    "1",
                ])
                .current_dir(&dir)
                .stdout(Stdio::piped())
                .stderr(Stdio::piped())
                .spawn()
                .unwrap();
            // s_server accepts exactly once, so the first TCP connection that
            // succeeds must be the TLS one: no readiness probe.
            let sock = connect_retry(port);
            let mut tls = TlsStream::connect(sock, Arc::new(cfg), "server.test")
                .unwrap_or_else(|e| panic!("{key_name} / {ossl_group}: {e}"));
            tls.write_all(b"GET / HTTP/1.0\r\n\r\n").unwrap();
            let mut body = Vec::new();
            let _ = tls.read_to_end(&mut body);
            let text = String::from_utf8_lossy(&body);
            assert!(
                text.starts_with("HTTP/1.0 200"),
                "{key_name} / {ossl_group}: {text}"
            );
            assert_eq!(tls.report().group, Some(*group));
            let _ = server.kill();
            let _ = server.wait();
        }
    }
}

fn connect_retry(port: u16) -> TcpStream {
    let deadline = Instant::now() + Duration::from_secs(20);
    loop {
        match TcpStream::connect(("127.0.0.1", port)) {
            Ok(s) => {
                s.set_read_timeout(Some(Duration::from_secs(20))).unwrap();
                return s;
            }
            Err(e) if Instant::now() > deadline => panic!("connect {port}: {e}"),
            Err(_) => std::thread::sleep(Duration::from_millis(50)),
        }
    }
}

/// Run our server for one connection on a thread; return the port.
fn serve_once(
    config: ServerConfig,
) -> (
    u16,
    std::thread::JoinHandle<Result<iron_socket_layer::report::SessionReport, String>>,
) {
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    let h = std::thread::spawn(move || {
        let (sock, _) = listener.accept().map_err(|e| e.to_string())?;
        sock.set_read_timeout(Some(Duration::from_secs(20)))
            .unwrap();
        let mut tls = TlsStream::accept(sock, Arc::new(config)).map_err(|e| e.to_string())?;
        let mut line = [0u8; 64];
        let n = tls.read(&mut line).map_err(|e| e.to_string())?;
        tls.write_all(&line[..n]).map_err(|e| e.to_string())?;
        let _ = tls.close();
        Ok(tls.report().clone())
    });
    (port, h)
}

fn s_client(dir: &Path, port: u16, group: &str, extra: &[&str]) -> String {
    let port_arg = format!("127.0.0.1:{port}");
    let mut args = vec![
        "s_client",
        "-connect",
        &port_arg,
        "-tls1_3",
        "-groups",
        group,
        "-CAfile",
        "ca.pem",
        "-verify_return_error",
        "-servername",
        "server.test",
        "-verify_hostname",
        "server.test",
        "-brief",
    ];
    args.extend_from_slice(extra);
    let mut child = Command::new("openssl")
        .args(&args)
        .current_dir(dir)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.take().unwrap().write_all(b"hello\n").unwrap();
    let out = child.wait_with_output().unwrap();
    format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    )
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn openssl_client_against_our_server_for_every_key_and_group() {
    for &kind in KeyKind::ALL {
        let pki = Pki::new(kind, "server.test");
        let dir = workdir(&format!("srv-{}", kind.id().replace(':', "-")));
        std::fs::write(dir.join("ca.pem"), der_to_pem(&pki.ca_cert)).unwrap();
        for (group, ossl_group) in GROUPS {
            let mut sc = pki.server_config(Profile::Default);
            sc.common.groups = vec![*group];
            let (port, h) = serve_once(sc);
            let out = s_client(&dir, port, ossl_group, &[]);
            let report = h
                .join()
                .unwrap()
                .unwrap_or_else(|e| panic!("{kind:?} / {ossl_group}: {e}\n{out}"));
            assert!(
                out.contains("Verification: OK"),
                "{kind:?} / {ossl_group}: OpenSSL did not verify our chain\n{out}"
            );
            assert_eq!(report.group, Some(*group));
        }
    }
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn openssl_client_certificate_is_verified_by_our_server() {
    let pki = Pki::new(KeyKind::EcdsaP256, "server.test");
    for (key_name, key_args) in KEYS {
        let dir = workdir(&format!("mtls-{key_name}"));
        std::fs::write(dir.join("ca.pem"), der_to_pem(&pki.ca_cert)).unwrap();
        openssl_identity(&dir, key_args);
        let client_cert = pem_to_der(&std::fs::read_to_string(dir.join("cert.pem")).unwrap());
        let mut client_roots = RootStore::new();
        client_roots.add_der(&client_cert).unwrap();
        let sc = pki
            .server_config(Profile::Default)
            .with_client_auth(ClientAuth::Required(PeerVerification::Roots(client_roots)));
        let (port, h) = serve_once(sc);
        let out = s_client(
            &dir,
            port,
            "X25519MLKEM768",
            &["-cert", "cert.pem", "-key", "key.pem"],
        );
        let report = h
            .join()
            .unwrap()
            .unwrap_or_else(|e| panic!("{key_name}: {e}\n{out}"));
        assert!(report.has(Property::MutualAuthentication), "{key_name}");
        assert_eq!(report.peer_subject_cn.as_deref(), Some("server.test"));
    }
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn our_client_resumes_with_openssl_server() {
    let dir = workdir("resume-client");
    openssl_identity(
        &dir,
        &["-newkey", "ec", "-pkeyopt", "ec_paramgen_curve:P-256"],
    );
    let cert_der = pem_to_der(&std::fs::read_to_string(dir.join("cert.pem")).unwrap());
    let mut roots = RootStore::new();
    roots.add_der(&cert_der).unwrap();
    let cfg = Arc::new(ClientConfig::new(Profile::Default, roots).unwrap());
    let port = free_port();
    let mut server = Command::new("openssl")
        .args([
            "s_server",
            "-accept",
            &port.to_string(),
            "-tls1_3",
            "-key",
            "key.pem",
            "-cert",
            "cert.pem",
            "-www",
            "-naccept",
            "2",
        ])
        .current_dir(&dir)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();
    let mut reports = Vec::new();
    for _ in 0..2 {
        let sock = connect_retry(port);
        let mut tls = TlsStream::connect(sock, cfg.clone(), "server.test").unwrap();
        tls.write_all(b"GET / HTTP/1.0\r\n\r\n").unwrap();
        let mut body = Vec::new();
        let _ = tls.read_to_end(&mut body);
        assert!(String::from_utf8_lossy(&body).starts_with("HTTP/1.0 200"));
        reports.push(tls.report().clone());
    }
    let _ = server.kill();
    let _ = server.wait();
    assert!(
        !reports[0].resumed && reports[0].tickets_received > 0,
        "{}",
        reports[0].to_json()
    );
    assert!(reports[1].resumed, "{}", reports[1].to_json());
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn openssl_client_resumes_with_our_server() {
    let pki = Pki::new(KeyKind::EcdsaP256, "server.test");
    let dir = workdir("resume-server");
    std::fs::write(dir.join("ca.pem"), der_to_pem(&pki.ca_cert)).unwrap();
    let _ = std::fs::remove_file(dir.join("sess.pem"));
    let config = Arc::new(pki.server_config(Profile::Default));
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    let h = std::thread::spawn(move || {
        let mut out = Vec::new();
        for _ in 0..2 {
            let (sock, _) = listener.accept().unwrap();
            sock.set_read_timeout(Some(Duration::from_secs(20)))
                .unwrap();
            let mut tls = TlsStream::accept(sock, config.clone()).unwrap();
            let mut line = [0u8; 64];
            let n = tls.read(&mut line).unwrap_or(0);
            let _ = tls.write_all(&line[..n]);
            let _ = tls.close();
            out.push(tls.report().clone());
        }
        out
    });
    let first = s_client(&dir, port, "X25519MLKEM768", &["-sess_out", "sess.pem"]);
    assert!(
        dir.join("sess.pem").exists(),
        "OpenSSL stored no session\n{first}"
    );
    // Without -brief so OpenSSL prints whether the session was reused.
    let port_arg = format!("127.0.0.1:{port}");
    let mut child = Command::new("openssl")
        .args([
            "s_client",
            "-connect",
            &port_arg,
            "-tls1_3",
            "-CAfile",
            "ca.pem",
            "-servername",
            "server.test",
            "-sess_in",
            "sess.pem",
        ])
        .current_dir(&dir)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.take().unwrap().write_all(b"hello\n").unwrap();
    let out = child.wait_with_output().unwrap();
    let text = String::from_utf8_lossy(&out.stdout);
    let reports = h.join().unwrap();
    assert!(
        text.contains("Reused, TLSv1.3"),
        "OpenSSL did not resume:\n{text}"
    );
    assert!(!reports[0].resumed && reports[1].resumed);
}

/// Build an OpenSSL CA, a leaf for server.test and an OCSP response for it
/// from an index in which the leaf has status `flag` (`V` or `R`).
fn openssl_ocsp_fixture(dir: &Path, flag: char, digest: &str) {
    let run = |args: &[&str]| {
        let out = openssl(args, dir);
        assert!(
            out.status.success(),
            "openssl {args:?}: {}",
            String::from_utf8_lossy(&out.stderr)
        );
    };
    run(&[
        "req",
        "-x509",
        "-newkey",
        "ec",
        "-pkeyopt",
        "ec_paramgen_curve:P-256",
        "-nodes",
        "-keyout",
        "ca.key",
        "-out",
        "ca.pem",
        "-subj",
        "/CN=OCSP Interop CA",
        "-days",
        "2",
        "-addext",
        "basicConstraints=critical,CA:TRUE",
        "-addext",
        "keyUsage=critical,keyCertSign,cRLSign",
    ]);
    run(&[
        "req",
        "-new",
        "-newkey",
        "ec",
        "-pkeyopt",
        "ec_paramgen_curve:P-256",
        "-nodes",
        "-keyout",
        "leaf.key",
        "-out",
        "leaf.csr",
        "-subj",
        "/CN=server.test",
    ]);
    std::fs::write(
        dir.join("ext.cnf"),
        "subjectAltName=DNS:server.test\nbasicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature\nextendedKeyUsage=serverAuth\n",
    )
    .unwrap();
    run(&[
        "x509",
        "-req",
        "-in",
        "leaf.csr",
        "-CA",
        "ca.pem",
        "-CAkey",
        "ca.key",
        "-set_serial",
        "0x1234",
        "-days",
        "1",
        "-out",
        "leaf.pem",
        "-extfile",
        "ext.cnf",
    ]);
    let line = match flag {
        'R' => "R\t300101000000Z\t250101000000Z\t1234\tunknown\t/CN=server.test\n",
        _ => "V\t300101000000Z\t\t1234\tunknown\t/CN=server.test\n",
    };
    std::fs::write(dir.join("index.txt"), line).unwrap();
    // The CertID digest option must precede -cert.
    let mut args = vec![
        "ocsp",
        "-index",
        "index.txt",
        "-rsigner",
        "ca.pem",
        "-rkey",
        "ca.key",
        "-CA",
        "ca.pem",
        "-issuer",
        "ca.pem",
    ];
    if !digest.is_empty() {
        args.push(digest);
    }
    args.extend_from_slice(&["-cert", "leaf.pem", "-respout", "resp.der", "-ndays", "1"]);
    run(&args);
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn our_client_verifies_openssl_staples() {
    use iron_socket_layer::config::Revocation;
    for (flag, digest) in [('V', ""), ('V', "-sha256"), ('R', "")] {
        let dir = workdir(&format!("ocsp-client-{flag}{digest}"));
        openssl_ocsp_fixture(&dir, flag, digest);
        let ca = pem_to_der(&std::fs::read_to_string(dir.join("ca.pem")).unwrap());
        let mut roots = RootStore::new();
        roots.add_der(&ca).unwrap();
        let mut cfg = ClientConfig::new(Profile::Default, roots).unwrap();
        cfg.revocation = Revocation::RequireStaple;
        let port = free_port();
        let mut server = Command::new("openssl")
            .args([
                "s_server",
                "-accept",
                &port.to_string(),
                "-tls1_3",
                "-key",
                "leaf.key",
                "-cert",
                "leaf.pem",
                "-status_file",
                "resp.der",
                "-www",
                "-naccept",
                "1",
            ])
            .current_dir(&dir)
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .unwrap();
        let sock = connect_retry(port);
        let result = TlsStream::connect(sock, Arc::new(cfg), "server.test");
        let _ = server.kill();
        let _ = server.wait();
        match flag {
            'R' => {
                let e = result.expect_err("a revoked certificate was accepted");
                assert!(e.to_string().contains("error:certificate-revoked"), "{e}");
            }
            _ => {
                let tls = result.unwrap_or_else(|e| panic!("{digest}: {e}"));
                assert_eq!(tls.report().revocation, "revocation:good");
                assert!(tls.report().has(Property::RevocationChecked));
            }
        }
    }
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn openssl_verifies_our_staples() {
    use iron_socket_layer::x509::ocsp::CertStatus;
    let pki = Pki::new(KeyKind::EcdsaP256, "server.test");
    let dir = workdir("ocsp-server");
    std::fs::write(dir.join("ca.pem"), der_to_pem(&pki.ca_cert)).unwrap();
    std::fs::write(dir.join("leaf.pem"), der_to_pem(&pki.server_chain[0])).unwrap();
    let t = common::now();
    let good = pki.staple(CertStatus::Good, t - 60, t + 3600);
    std::fs::write(dir.join("resp.der"), &good).unwrap();

    // OpenSSL's own OCSP verifier accepts the response and reads its status.
    // Our CertIDs are SHA-256 (IronCrypto has no SHA-1), so OpenSSL must look
    // the certificate up by SHA-256 too; its default lookup is SHA-1.
    let out = openssl(
        &[
            "ocsp", "-respin", "resp.der", "-CAfile", "ca.pem", "-issuer", "ca.pem", "-sha256",
            "-cert", "leaf.pem",
        ],
        &dir,
    );
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
    assert!(text.contains("Response verify OK"), "{text}");
    assert!(text.contains("leaf.pem: good"), "{text}");

    // And s_client sees it stapled by our server.
    let mut sc = pki.server_config(Profile::Default);
    sc.identities[0] = sc.identities[0].clone().with_ocsp(good);
    let (port, h) = serve_once(sc);
    let port_arg = format!("127.0.0.1:{port}");
    let mut child = Command::new("openssl")
        .args([
            "s_client",
            "-connect",
            &port_arg,
            "-tls1_3",
            "-CAfile",
            "ca.pem",
            "-servername",
            "server.test",
            "-status",
        ])
        .current_dir(&dir)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.take().unwrap().write_all(b"hello\n").unwrap();
    let out = child.wait_with_output().unwrap();
    let text = String::from_utf8_lossy(&out.stdout);
    h.join().unwrap().unwrap();
    assert!(text.contains("OCSP Response Status: successful"), "{text}");
    assert!(text.contains("Cert Status: good"), "{text}");
}

fn crl_to_pem(der: &[u8]) -> String {
    let mut buf = vec![0u8; ic_pkix::pem::encoded_len("X509 CRL", der.len())];
    let n = ic_pkix::pem::encode("X509 CRL", der, &mut buf).unwrap();
    String::from_utf8(buf[..n].to_vec()).unwrap()
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn openssl_honours_our_crls() {
    let pki = Pki::new(KeyKind::EcdsaP256, "server.test");
    let leaf = &pki.server_chain[0];
    let serial = iron_socket_layer::x509::Certificate::parse(leaf)
        .unwrap()
        .serial()
        .to_vec();
    for (revoke, expect) in [(false, "leaf.pem: OK"), (true, "certificate revoked")] {
        let dir = workdir(&format!("crl-ours-{revoke}"));
        std::fs::write(dir.join("ca.pem"), der_to_pem(&pki.ca_cert)).unwrap();
        std::fs::write(dir.join("leaf.pem"), der_to_pem(leaf)).unwrap();
        let revoked: Vec<&[u8]> = if revoke { vec![&serial] } else { vec![] };
        std::fs::write(dir.join("crl.pem"), crl_to_pem(&pki.crl(&revoked))).unwrap();
        let out = openssl(
            &["crl", "-in", "crl.pem", "-CAfile", "ca.pem", "-noout"],
            &dir,
        );
        let text = format!(
            "{}{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        );
        assert!(
            text.contains("verify OK"),
            "OpenSSL rejected our CRL signature: {text}"
        );
        let out = openssl(
            &[
                "verify",
                "-crl_check",
                "-CAfile",
                "ca.pem",
                "-CRLfile",
                "crl.pem",
                "leaf.pem",
            ],
            &dir,
        );
        let text = format!(
            "{}{}",
            String::from_utf8_lossy(&out.stdout),
            String::from_utf8_lossy(&out.stderr)
        );
        assert!(text.contains(expect), "revoke={revoke}: {text}");
    }
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn our_path_validation_honours_openssl_crls() {
    use iron_socket_layer::x509::{self, crl::CrlStore, Usage, VerifyOptions};
    for flag in ['V', 'R'] {
        let dir = workdir(&format!("crl-openssl-{flag}"));
        openssl_ocsp_fixture(&dir, flag, "");
        std::fs::write(dir.join("crlnumber"), "01\n").unwrap();
        std::fs::write(
            dir.join("ca.cnf"),
            "[ ca ]\ndefault_ca = d\n[ d ]\ndatabase = index.txt\ncrlnumber = crlnumber\ndefault_md = sha256\ndefault_crl_days = 1\n",
        )
        .unwrap();
        let out = openssl(
            &[
                "ca", "-config", "ca.cnf", "-gencrl", "-keyfile", "ca.key", "-cert", "ca.pem",
                "-out", "crl.pem",
            ],
            &dir,
        );
        assert!(
            out.status.success(),
            "{}",
            String::from_utf8_lossy(&out.stderr)
        );
        let mut crls = CrlStore::new();
        assert_eq!(
            crls.add_pem(&std::fs::read_to_string(dir.join("crl.pem")).unwrap())
                .unwrap(),
            1
        );
        let mut roots = RootStore::new();
        roots
            .add_der(&pem_to_der(
                &std::fs::read_to_string(dir.join("ca.pem")).unwrap(),
            ))
            .unwrap();
        let leaf = pem_to_der(&std::fs::read_to_string(dir.join("leaf.pem")).unwrap());
        let mut opts = VerifyOptions::new(
            common::now(),
            Usage::ServerAuth,
            iron_socket_layer::crypto::sign::VERIFY_SCHEMES,
        );
        opts.crls = Some(&crls);
        opts.require_crl = true;
        let r = x509::verify_chain(&leaf, &[], &roots, &opts);
        match flag {
            'R' => assert_eq!(
                r.unwrap_err().kind(),
                iron_socket_layer::ErrorKind::CertificateRevoked
            ),
            _ => assert!(r.unwrap().crl_checked),
        }
    }
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn openssl_answers_our_post_handshake_certificate_request() {
    let pki = Pki::new(KeyKind::EcdsaP256, "server.test");
    let dir = workdir("pha");
    std::fs::write(dir.join("ca.pem"), der_to_pem(&pki.ca_cert)).unwrap();
    openssl_identity(
        &dir,
        &["-newkey", "ec", "-pkeyopt", "ec_paramgen_curve:P-256"],
    );
    let client_cert = pem_to_der(&std::fs::read_to_string(dir.join("cert.pem")).unwrap());
    let mut client_roots = RootStore::new();
    client_roots.add_der(&client_cert).unwrap();
    let sc = Arc::new(
        pki.server_config(Profile::Default)
            .with_client_auth(ClientAuth::OnDemand(PeerVerification::Roots(client_roots))),
    );
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    let h = std::thread::spawn(move || {
        let (sock, _) = listener.accept().unwrap();
        sock.set_read_timeout(Some(Duration::from_secs(20)))
            .unwrap();
        let mut tls = TlsStream::accept(sock, sc).unwrap();
        let mut line = [0u8; 64];
        let n = tls.read(&mut line).unwrap();
        assert!(!tls.report().has(Property::MutualAuthentication));
        // Step up: ask for a certificate now, then keep reading.
        tls.connection().request_client_auth().unwrap();
        tls.flush().unwrap();
        let _ = tls.read(&mut line[n..]);
        let report = tls.report().clone();
        let _ = tls.close();
        report
    });
    let port_arg = format!("127.0.0.1:{port}");
    let mut child = Command::new("openssl")
        .args([
            "s_client",
            "-connect",
            &port_arg,
            "-tls1_3",
            "-CAfile",
            "ca.pem",
            "-servername",
            "server.test",
            "-enable_pha",
            "-cert",
            "cert.pem",
            "-key",
            "key.pem",
            "-quiet",
        ])
        .current_dir(&dir)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    let mut stdin = child.stdin.take().unwrap();
    stdin.write_all(b"first\n").unwrap();
    std::thread::sleep(Duration::from_millis(1500));
    stdin.write_all(b"second\n").unwrap();
    std::thread::sleep(Duration::from_millis(1500));
    drop(stdin);
    let report = h.join().unwrap();
    let _ = child.kill();
    let _ = child.wait();
    assert!(
        report.has(Property::MutualAuthentication),
        "{}",
        report.to_json()
    );
    assert!(report
        .events
        .iter()
        .any(|e| e.id == "event:post-handshake-auth" && e.detail == "verified"));
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn external_psk_with_openssl_both_ways() {
    use iron_socket_layer::config::ExternalPsk;
    use iron_socket_layer::crypto::HashAlg;
    let key = [0x42u8; 32];
    let hex: String = key.iter().map(|b| format!("{b:02x}")).collect();
    let dir = workdir("psk");

    // Our client, OpenSSL server.
    let port = free_port();
    let mut server = Command::new("openssl")
        .args([
            "s_server",
            "-accept",
            &port.to_string(),
            "-tls1_3",
            "-psk",
            &hex,
            "-psk_identity",
            "sensor-17",
            "-nocert",
            "-www",
            "-naccept",
            "1",
        ])
        .current_dir(&dir)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();
    let cfg = ClientConfig::external_psk(
        Profile::Default,
        ExternalPsk::new(b"sensor-17", &key, HashAlg::Sha256).unwrap(),
    )
    .unwrap();
    let mut tls = TlsStream::connect(connect_retry(port), Arc::new(cfg), "localhost").unwrap();
    tls.write_all(b"GET / HTTP/1.0\r\n\r\n").unwrap();
    let mut body = Vec::new();
    let _ = tls.read_to_end(&mut body);
    let _ = server.kill();
    let _ = server.wait();
    assert!(String::from_utf8_lossy(&body).starts_with("HTTP/1.0 200"));
    assert!(
        tls.report().has(Property::PskAuthenticated),
        "{}",
        tls.report().to_json()
    );

    // OpenSSL client, our server.
    let sc = iron_socket_layer::config::ServerConfig::external_psk_only(
        Profile::Default,
        vec![ExternalPsk::new(b"sensor-17", &key, HashAlg::Sha256).unwrap()],
    )
    .unwrap();
    let (port, h) = serve_once(sc);
    let port_arg = format!("127.0.0.1:{port}");
    let mut child = Command::new("openssl")
        .args([
            "s_client",
            "-connect",
            &port_arg,
            "-tls1_3",
            "-psk",
            &hex,
            "-psk_identity",
            "sensor-17",
            "-brief",
        ])
        .current_dir(&dir)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    child.stdin.take().unwrap().write_all(b"hello\n").unwrap();
    let out = child.wait_with_output().unwrap();
    let report = h
        .join()
        .unwrap()
        .unwrap_or_else(|e| panic!("{e}\n{}", String::from_utf8_lossy(&out.stderr)));
    assert!(report.has(Property::PskAuthenticated));
    // psk_dhe_ke: OpenSSL and we still ran a fresh key exchange.
    assert!(report.group.is_some(), "{}", report.to_json());
    assert!(report.has(Property::ForwardSecrecy));
}

/// Pump a sans-I/O connection over a socket until the handshake completes
/// (or fails), then give the socket a moment for post-handshake messages.
fn drive(conn: &mut iron_socket_layer::Connection, sock: &mut TcpStream) {
    let mut buf = vec![0u8; 32 * 1024];
    sock.set_read_timeout(Some(Duration::from_millis(1500)))
        .unwrap();
    for _ in 0..50 {
        let out = conn.take_tls();
        if !out.is_empty() {
            sock.write_all(&out).unwrap();
        }
        match sock.read(&mut buf) {
            Ok(0) => break,
            Ok(n) => {
                if conn.read_tls(&buf[..n]).is_err() {
                    break;
                }
            }
            Err(_) if !conn.is_handshaking() => break,
            Err(_) => {}
        }
    }
    let _ = sock.write_all(&conn.take_tls());
}

#[test]
#[ignore = "needs openssl 3.5+ on PATH"]
fn early_data_with_openssl_both_ways() {
    use iron_socket_layer::config::EarlyDataPolicy;
    use iron_socket_layer::Connection;
    const EARLY: &[u8] = b"early hello from iron-socket-layer\n";

    // Our client, OpenSSL server.
    let dir = workdir("0rtt-client");
    openssl_identity(
        &dir,
        &["-newkey", "ec", "-pkeyopt", "ec_paramgen_curve:P-256"],
    );
    let mut roots = RootStore::new();
    roots
        .add_der(&pem_to_der(
            &std::fs::read_to_string(dir.join("cert.pem")).unwrap(),
        ))
        .unwrap();
    let mut cfg = ClientConfig::new(Profile::Default, roots).unwrap();
    cfg.early_data = true;
    let cfg = Arc::new(cfg);
    let port = free_port();
    let mut server = Command::new("openssl")
        .args([
            "s_server",
            "-accept",
            &port.to_string(),
            "-tls1_3",
            "-key",
            "key.pem",
            "-cert",
            "cert.pem",
            "-early_data",
            "-www",
            "-naccept",
            "2",
        ])
        .current_dir(&dir)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .unwrap();
    let mut first = Connection::client(cfg.clone(), "server.test").unwrap();
    let mut sock = connect_retry(port);
    drive(&mut first, &mut sock);
    // s_server issues tickets only in -www mode (interactive mode sends none
    // in OpenSSL 3.5); a request makes it answer, after the tickets.
    first
        .send(
            b"GET / HTTP/1.0

",
        )
        .unwrap();
    drive(&mut first, &mut sock);
    first.close();
    let _ = sock.write_all(&first.take_tls());
    assert!(
        first.report().tickets_received > 0,
        "{}",
        first.report().to_json()
    );
    // The HTTP request itself goes as 0-RTT data, and nothing is sent after
    // the handshake: an HTTP response proves OpenSSL received and acted on it.
    let request = b"GET / HTTP/1.0

";
    let mut second = Connection::client_with_early_data(cfg, "server.test", request).unwrap();
    drive(&mut second, &mut connect_retry(port));
    let _ = server.kill();
    let _ = server.wait();
    assert_eq!(
        second.report().early_data,
        "early-data:accepted",
        "{}",
        second.report().to_json()
    );
    let mut resp = vec![0u8; 64 * 1024];
    let n = second.recv(&mut resp);
    let resp = String::from_utf8_lossy(&resp[..n]);
    assert!(
        resp.starts_with("HTTP/1.0 200"),
        "no response to the 0-RTT request: {resp:?}"
    );

    // OpenSSL client, our server.
    let pki = Pki::new(KeyKind::EcdsaP256, "server.test");
    let dir = workdir("0rtt-server");
    std::fs::write(dir.join("ca.pem"), der_to_pem(&pki.ca_cert)).unwrap();
    std::fs::write(dir.join("early.txt"), EARLY).unwrap();
    let _ = std::fs::remove_file(dir.join("sess.pem"));
    let mut sc = pki.server_config(Profile::Default);
    sc.early_data = Some(EarlyDataPolicy::new(16_384));
    let sc = Arc::new(sc);
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let port = listener.local_addr().unwrap().port();
    let h = std::thread::spawn(move || {
        let mut out = Vec::new();
        for _ in 0..2 {
            let (mut sock, _) = listener.accept().unwrap();
            let mut conn = Connection::server(sc.clone()).unwrap();
            drive(&mut conn, &mut sock);
            let mut data = vec![0u8; 256];
            let n = conn.recv(&mut data);
            data.truncate(n);
            out.push((conn.report().clone(), data));
        }
        out
    });
    let port_arg = format!("127.0.0.1:{port}");
    let s_client = |extra: &[&str]| {
        let mut args = vec![
            "s_client",
            "-connect",
            &port_arg,
            "-tls1_3",
            "-CAfile",
            "ca.pem",
            "-servername",
            "server.test",
        ];
        args.extend_from_slice(extra);
        let mut child = Command::new("openssl")
            .args(&args)
            .current_dir(&dir)
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap();
        let mut stdin = child.stdin.take().unwrap();
        std::thread::sleep(Duration::from_millis(1200));
        let _ = stdin.write_all(b"\n");
        drop(stdin);
        child.wait_with_output().unwrap()
    };
    let _ = s_client(&["-sess_out", "sess.pem"]);
    let out = s_client(&["-sess_in", "sess.pem", "-early_data", "early.txt"]);
    let results = h.join().unwrap();
    let (report, data) = &results[1];
    let text = String::from_utf8_lossy(&out.stdout);
    assert_eq!(
        report.early_data,
        "early-data:accepted",
        "{}\n{text}",
        report.to_json()
    );
    assert!(
        data.starts_with(EARLY),
        "server received {:?}",
        String::from_utf8_lossy(data)
    );
    assert!(text.contains("Early data was accepted"), "{text}");
}
